name: koodisto-app
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install mock dependencies
        run: cd mock-api && npm install && cd -
      - name: Run Cypress tests
        run: npm run cypress:ci

  react-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install mock dependencies
        run: cd mock-api && npm install && cd -
      - name: Run react Build
        run: npm run build
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Maven version
        run: mvn --version
      - name: Build Spring-Boot
        run: cd server && mvn clean install && cd -
      - name: Upload koodisto-app-spring-boot
        uses: actions/upload-artifact@v2
        with:
          name: koodisto-app-spring-boot
          path: server/target/koodisto-app.jar

  deploy-container:
    needs: [cypress,react-build]
    runs-on: ubuntu-latest
    steps:
      - name: Download koodisto-app-spring-boot
        uses: actions/download-artifact@v2
        with:
          name: koodisto-app-spring-boot
      - name: Build Docker Conainer
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
          export ARTIFACT_NAME="koodisto-app"
          mv koodisto-app.jar $DOCKER_BUILD_DIR/artifact/$ARTIFACT_NAME.jar
          touch $DOCKER_BUILD_DIR/config/empty.props
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
